from dataclasses import FrozenInstanceError
from hashlib import sha256
from pathlib import Path

import pytest

from scripts.render_plan import (
    GENERATOR_VERSION,
    PhaseSummary,
    PlanRenderError,
    PlanSummary,
    build_html,
    main,
    parse_plan,
)


SAMPLE_PLAN = """# Demo plan

## Phase 0：脚手架
- [x] 创建目录
- [x] 写基础测试

## Phase 1：数据
- [ ] 下载数据
- [x] 校验样本

## Phase 2：评测
- [ ] 运行评测
"""


def test_main_writes_output_and_checks_for_stale_content(tmp_path: Path) -> None:
    source = tmp_path / "plan.md"
    output = tmp_path / "nested" / "plan.html"
    source.write_text(
        """## Phase 1: Prepare
- [x] Gather input

## Phase 2: Deliver
- [ ] Publish output
""",
        encoding="utf-8",
    )

    assert main([str(source), "--output", str(output)]) == 0
    assert output.is_file()
    assert main([str(source), "--output", str(output), "--check"]) == 0

    output.write_text("stale", encoding="utf-8")

    assert main([str(source), "--output", str(output), "--check"]) == 1
    assert output.read_text(encoding="utf-8") == "stale"


def test_main_returns_error_without_writing_for_invalid_markdown(tmp_path: Path) -> None:
    source = tmp_path / "invalid.md"
    output = tmp_path / "invalid.html"
    source.write_text("# Not a plan\n", encoding="utf-8")

    assert main([str(source), "--output", str(output)]) == 2
    assert not output.exists()


def test_main_reports_invalid_utf8_without_writing_output(tmp_path: Path, capsys) -> None:
    source = tmp_path / "invalid-encoding.md"
    output = tmp_path / "invalid-encoding.html"
    source.write_bytes(b"\xff")

    assert main([str(source), "--output", str(output)]) == 2
    assert not output.exists()
    assert "render-plan:" in capsys.readouterr().err


def test_main_reports_missing_source_without_writing_output(tmp_path: Path, capsys) -> None:
    source = tmp_path / "missing.md"
    output = tmp_path / "missing.html"

    assert main([str(source), "--output", str(output)]) == 2
    assert not output.exists()
    assert "render-plan:" in capsys.readouterr().err


def test_main_checks_default_output_from_any_working_directory(
    tmp_path: Path, monkeypatch
) -> None:
    monkeypatch.chdir(tmp_path)

    assert main(["--check"]) == 0


def test_build_html_contains_dashboard_navigation_source_hash_and_markdown_body() -> None:
    source = Path("docs/plans/demo.md")
    rendered = build_html(source, SAMPLE_PLAN)
    assert "7 / 5" not in rendered
    assert "3 / 5" in rendered
    assert 'href="#phase-0"' in rendered
    assert 'id="phase-1"' in rendered
    assert "Demo plan" in rendered
    assert "创建目录" in rendered
    assert "SHA-256" in rendered
    assert "<!doctype html>" in rendered.lower()


def test_build_html_is_byte_stable_for_the_same_input() -> None:
    source = Path("docs/plans/demo.md")
    assert build_html(source, SAMPLE_PLAN) == build_html(source, SAMPLE_PLAN)


def test_build_html_marks_its_generator_and_version_in_a_comment() -> None:
    rendered = build_html(Path("docs/plans/demo.md"), SAMPLE_PLAN)

    assert (
        f"<!-- Generated by scripts/render_plan.py v{GENERATOR_VERSION}; "
        "do not edit manually. -->"
    ) in rendered


def test_build_html_labels_completed_current_and_pending_phase_states() -> None:
    rendered = build_html(Path("docs/plans/demo.md"), SAMPLE_PLAN)

    assert (
        '<li class="phase-state completed" data-state="completed">'
        '<a href="#phase-0"'
    ) in rendered
    assert "已完成" in rendered
    assert (
        '<li class="phase-state current" data-state="current">'
        '<a href="#phase-1"'
    ) in rendered
    assert "进行中" in rendered
    assert (
        '<li class="phase-state pending" data-state="pending">'
        '<a href="#phase-2"'
    ) in rendered
    assert "待开始" in rendered


def test_build_html_includes_the_exact_utf8_hash_and_posix_source_path() -> None:
    source = Path("docs/plans/demo.md")
    rendered = build_html(source, SAMPLE_PLAN)

    assert sha256(SAMPLE_PLAN.encode("utf-8")).hexdigest() in rendered
    assert "docs/plans/demo.md" in rendered


def test_build_html_preserves_gfm_content_and_phase_links() -> None:
    markdown = """# Fidelity plan

## Phase 4: Prepare
- [x] Collect input

| Name | Status |
| --- | --- |
| Demo | ready |

```python
print("ready")
```

## Phase 5: Execute
- [ ] Run process
"""

    rendered = build_html(Path("docs/plans/fidelity.md"), markdown)

    assert "<table>" in rendered
    assert "<code" in rendered
    assert 'type="checkbox"' in rendered
    assert 'id="phase-4"' in rendered
    assert 'href="#phase-5"' in rendered


def test_parse_plan_rejects_duplicate_phase_numbers() -> None:
    markdown = """## Phase 1: First
- [x] Complete first task

## Phase 1: Duplicate
- [ ] Complete duplicate task
"""

    try:
        parse_plan(markdown)
    except PlanRenderError as error:
        assert "Phase" in str(error)
        assert "duplicate" in str(error).lower()
    else:
        raise AssertionError("expected PlanRenderError")


def test_build_html_downgrades_remote_images_without_network_sources() -> None:
    markdown = """## Phase 1: Source
- [x] Prepare image

![Remote image](https://example.invalid/image.png)

## Phase 2: Finish
- [ ] Publish report
"""

    rendered = build_html(Path("docs/plans/images.md"), markdown)

    assert 'src="https://' not in rendered
    assert 'src="http://' not in rendered
    assert "Remote image" in rendered


def test_build_html_downgrades_ftp_images_without_external_sources() -> None:
    markdown = """## Phase 1: Source
- [x] Prepare image

![FTP image](ftp://example.invalid/a.png)

## Phase 2: Finish
- [ ] Publish report
"""

    rendered = build_html(Path("docs/plans/images.md"), markdown)

    assert "<img" not in rendered
    assert "src=" not in rendered
    assert "FTP image" in rendered


def test_build_html_downgrades_protocol_relative_images_without_network_sources() -> None:
    markdown = """## Phase 1: Source
- [x] Prepare image

![Network image](//example.invalid/a.png)

## Phase 2: Finish
- [ ] Publish report
"""

    rendered = build_html(Path("docs/plans/images.md"), markdown)

    assert 'src="//example.invalid/a.png"' not in rendered
    assert '<img src="//' not in rendered
    assert "Network image" in rendered


@pytest.mark.parametrize(
    "image_source",
    [
        "https://example.invalid/a.png",
        "http://example.invalid/a.png",
        "HTTPS://example.invalid/a.png",
        "HtTp://example.invalid/a.png",
        "//example.invalid/a.png",
    ],
)
def test_build_html_downgrades_all_remote_image_url_forms(image_source: str) -> None:
    markdown = f"""## Phase 1: Source
- [x] Prepare image

![Network image]({image_source})

## Phase 2: Finish
- [ ] Publish report
"""

    rendered = build_html(Path("docs/plans/images.md"), markdown)

    assert f'<img src="{image_source}"' not in rendered
    assert 'src="http' not in rendered
    assert "Network image" in rendered


def test_build_html_downgrades_local_relative_images_without_resources() -> None:
    markdown = """## Phase 1: Source
- [x] Prepare image

![Local image](images/local.png)

## Phase 2: Finish
- [ ] Publish report
"""

    rendered = build_html(Path("docs/plans/images.md"), markdown)

    assert "<img" not in rendered
    assert "src=" not in rendered
    assert "Local image" in rendered


def test_build_html_uses_the_escaped_source_stem_for_title_and_heading() -> None:
    source = Path("docs/plans/release-plan.md")
    rendered = build_html(source, SAMPLE_PLAN)

    assert "<title>release-plan</title>" in rendered
    assert "<h1>release-plan</h1>" in rendered


def test_build_html_escapes_dangerous_source_stems_and_raw_markdown_html() -> None:
    markdown = """## Phase 1: Safe
- [x] Complete task

<script>alert("unsafe")</script>

## Phase 2: Next
- [ ] Pending task
"""

    rendered = build_html(Path("docs/plans/<unsafe&.md"), markdown)

    assert "<title>&lt;unsafe&amp;</title>" in rendered
    assert "<h1>&lt;unsafe&amp;</h1>" in rendered
    assert "<script>alert" not in rendered
    assert "&lt;script&gt;alert" in rendered


def test_parse_plan_summarizes_each_phase_and_global_tasks() -> None:
    summary = parse_plan(SAMPLE_PLAN)
    assert summary.total_tasks == 5
    assert summary.completed_tasks == 3
    assert [
        (phase.number, phase.completed_tasks, phase.total_tasks)
        for phase in summary.phases
    ] == [(0, 2, 2), (1, 1, 2), (2, 0, 1)]
    assert summary.current_phase_number == 1


def test_parse_plan_rejects_markdown_without_phases_or_tasks() -> None:
    try:
        parse_plan("# Notes\n\n- plain bullet")
    except PlanRenderError as error:
        assert "Phase" in str(error)
    else:
        raise AssertionError("expected PlanRenderError")


def test_parse_plan_ignores_headings_and_tasks_inside_code_blocks() -> None:
    summary = parse_plan(
        """## Phase 1: Parsing
- [x] Real task

This paragraph separates the following indented code block from the list.

    - [x] Indented code task

```markdown
## Phase 99: Example
- [x] Fenced code task
```

- [ ] Another real task
"""
    )

    assert [(phase.number, phase.completed_tasks, phase.total_tasks) for phase in summary.phases] == [
        (1, 1, 2)
    ]


def test_parse_plan_counts_all_gfm_task_list_markers() -> None:
    summary = parse_plan(
        """## Phase 1: GFM tasks
- [x] Dash task
+ [ ] Plus task
* [X] Star task
1. [ ] Ordered task
"""
    )

    assert summary.total_tasks == 4
    assert summary.completed_tasks == 2


def test_parse_plan_counts_nested_list_tasks() -> None:
    summary = parse_plan(
        """## Phase 1: Nested tasks
- [ ] Parent task
  - [x] Nested task
"""
    )

    assert summary.total_tasks == 2
    assert summary.completed_tasks == 1


def test_parse_plan_keeps_completed_state_for_task_with_continuation() -> None:
    summary = parse_plan(
        """## Phase 1: Complete
- [x] Done task
  Continuation text.

## Phase 2: Next
- [ ] Pending task
"""
    )

    assert [(phase.completed_tasks, phase.total_tasks) for phase in summary.phases] == [
        (1, 1),
        (0, 1),
    ]
    assert summary.current_phase_number == 2


def test_parse_plan_rejects_empty_phase_titles() -> None:
    for heading in ("## Phase 1:", "## Phase 1：   "):
        try:
            parse_plan(f"{heading}\n- [ ] Task")
        except PlanRenderError as error:
            assert "Phase" in str(error)
        else:
            raise AssertionError("expected PlanRenderError")


def test_parse_plan_rejects_phase_without_checkbox_tasks() -> None:
    try:
        parse_plan("## Phase 1: Empty\n\nA description without a checklist.")
    except PlanRenderError as error:
        assert "Phase" in str(error)
    else:
        raise AssertionError("expected PlanRenderError")


def test_parse_plan_rejects_any_empty_phase_when_other_phases_have_tasks() -> None:
    try:
        parse_plan(
            """## Phase 1: Empty

No checklist here.

## Phase 2: Task
- [ ] Real task
"""
        )
    except PlanRenderError as error:
        assert "Phase 1" in str(error)
    else:
        raise AssertionError("expected PlanRenderError")


def test_phase_summary_has_stable_anchor_and_is_frozen() -> None:
    phase = PhaseSummary(number=3, title="Review", completed_tasks=1, total_tasks=2)

    assert phase.anchor == "phase-3"
    try:
        phase.number = 4
    except FrozenInstanceError:
        pass
    else:
        raise AssertionError("expected FrozenInstanceError")


def test_plan_summary_is_frozen() -> None:
    summary = PlanSummary(
        phases=(), completed_tasks=0, total_tasks=0, current_phase_number=None
    )

    try:
        summary.total_tasks = 1
    except FrozenInstanceError:
        pass
    else:
        raise AssertionError("expected FrozenInstanceError")


def test_parse_plan_has_no_current_phase_when_all_tasks_are_complete() -> None:
    summary = parse_plan(
        """## Phase 1: First
- [x] Complete first task

## Phase 2: Second
- [x] Complete second task
"""
    )

    assert summary.current_phase_number is None
